name: Discord on-demand (GitHub-only)

on:
  workflow_dispatch:
    inputs:
      content:
        description: "Testo del messaggio da inviare a Discord"
        required: true
      username:
        description: "Nome visualizzato (opzionale)"
        required: false
        default: ""
      embeds_json:
        description: "JSON per embeds (opzionale)"
        required: false
        default: "[]"

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - name: Post to Discord (on-demand)
        env:
          WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          CONTENT: ${{ github.event.inputs.content }}
          USERNAME: ${{ github.event.inputs.username }}
          EMBEDS: ${{ github.event.inputs.embeds_json }}
        run: |
          # Normalizza EMBEDS: se non è JSON valido o è vuoto, metti []
          echo "$EMBEDS" > embeds_in.txt
          if ! jq -e . embeds_in.txt >/dev/null 2>&1; then
            echo "[]" > embeds.json
          else
            cat embeds_in.txt > embeds.json
          fi

          # Crea il payload in modo sicuro con jq (niente problemi di quoting)
          jq -n --arg c "$CONTENT" --arg u "$USERNAME" --slurpfile e embeds.json '
            {content:$c}
            + ( ($u|length)>0 ? {username:$u} : {} )
            + ( ( ($e[0]|type)=="array" and ($e[0]|length)>0 ) ? {embeds:$e[0]} : {} )
          ' > payload.json

          echo "Payload che invio:"
          cat payload.json

          curl -X POST -H "Content-Type: application/json" \
            -d @payload.json "$WEBHOOK_URL"
