name: Discord on-demand (GitHub-only)

on:
  workflow_dispatch:
    inputs:
      content:
        description: "Testo del messaggio da inviare a Discord"
        required: true
      username:
        description: "Nome visualizzato (opzionale)"
        required: false
        default: ""
      embeds_json:
        description: "JSON per embeds (opzionale)"
        required: false
        default: "[]"

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - name: Post to Discord (on-demand)
        env:
          WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          CONTENT: ${{ github.event.inputs.content }}
          USERNAME: ${{ github.event.inputs.username }}
          EMBEDS: ${{ github.event.inputs.embeds_json }}
        shell: bash
        run: |
          python - <<'PY' > payload.json
import os, json

content  = os.environ.get("CONTENT", "")
username = os.environ.get("USERNAME", "")
embeds_s = os.environ.get("EMBEDS", "[]")

# Prova a leggere gli embeds; se non è JSON valido -> []
try:
    embeds = json.loads(embeds_s)
except Exception:
    embeds = []

payload = {"content": content}
if isinstance(username, str) and len(username) > 0:
    payload["username"] = username
if isinstance(embeds, list) and len(embeds) > 0:
    payload["embeds"] = embeds

print(json.dumps(payload))
PY

          echo "Payload che invio:"
          cat payload.json

          curl -X POST -H "Content-Type: application/json" \
            -d @payload.json "$WEBHOOK_URL"
